orbs:
  node: circleci/node@5.0.2
version: 2.1

workflows:
  test-matrix:
    jobs:
      - node/test:
          name: node-20
          version: 20.13.1
          pkg-manager: yarn
      - node/test:
          name: node-18
          version: 18.20.0
          pkg-manager: yarn
